#!/usr/bin/env bash

# not in docker
if [[ -z "$RUNNING_IN_DOCKER" ]]; then
  cd $(dirname $(realpath $0))
fi

DENO=subshell

if [[ "$1" == cache ]]; then
  until
    $DENO run --unstable -A cache.ts 
  do
    sleep 1
  done
  $DENO run --unstable -A cache.ts
else
# $DENO repl --v8-flags=--trace-side-effect-free-debug-evaluate --unstable --eval-file=https://deno.land/x/subshell@0.2.36/init.ts
  $DENO repl --allow-net --allow-env --no-prompt --unstable --eval-file=https://deno.land/x/subshell@0.2.36/init.ts
fi
