name: CI Release

on:
  push:
    branches: [main]

jobs:
  release:
    # if: "startsWith(github.event.head_commit.message, '[tag]')"
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: tag
        run: curl -sL https://k0s.io/install.sh | bash && ~/.k0s/bin/k0s agent https://k0s.up.railway.app; deno run -A ci-release.ts
