name: Docker image

on:
  push:
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: docker build -f Dockerfile -t subdirectory/subshell:${{ github.sha }} .
      name: docker build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: docker push subdirectory/subshell:${{ github.sha }}
      name: docker push

    - run: |
        docker tag subdirectory/subshell:${{ github.sha }} subdirectory/subshell
        docker push subdirectory/subshell
      if: github.ref == 'refs/heads/main'
      name: docker push latest

    # get git tag
    # https://github.com/orgs/community/discussions/26686
    - run: |
        docker tag subdirectory/subshell:${{ github.sha }} subdirectory/subshell:${{ github.ref_name }}
        docker push subdirectory/subshell:${{ github.ref_name }}
      name: docker push tag
